package com.lumeai.banking.models

import java.util.Date

/**
 * Core data model representing an AI decision made by a bank
 * This is what banks send to LumeAI for explanation and bias checking
 */
data class BankAIDecision(
    val decisionType: String,  // "loan_denied", "transaction_blocked", "credit_limit_reduced"
    val outcome: String,        // "DENIED", "APPROVED", "BLOCKED"
    val factors: List<DecisionFactor>,
    val actionableSteps: List<String>,
    val biasWarning: String?,
    val timestamp: Long
)

/**
 * Individual factor that influenced the AI decision
 */
data class DecisionFactor(
    val technicalName: String,      // e.g., "credit_score"
    val friendlyName: String,        // Simple language: "Credit Score"
    val impact: String,              // "HIGH", "MEDIUM", "LOW"  
    val value: String,               // Actual value: "620"
    val explanation: String,         // Why this matters
    val fairnessFlag: FairnessFlag?  // Optional bias flag
)

/**
 * Flags potential bias or fairness issues in a decision factor
 */
data class FairnessFlag(
    val isFlagged: Boolean,
    val reason: String,  // "May disadvantage rural/elderly users"
    val severity: String // "HIGH", "MEDIUM", "LOW"
)

/**
 * Raw decision from bank's AI system before explanation
 */
data class BankDecision(
    val customerId: String,
    val decisionType: String,
    val timestamp: Long,
    val factors: List<RawDecisionFactor>,
    val customerProfile: CustomerProfile
)

/**
 * Raw decision factor as provided by bank's AI
 */
data class RawDecisionFactor(
    val technicalName: String,
    val value: String,
    val weight: Double,      // Importance in decision (0.0 - 1.0)
    val threshold: String,   // Required value
    val passed: Boolean      // Did customer meet this requirement?
)

/**
 * Customer profile for personalized explanations and bias detection
 */
data class CustomerProfile(
    val age: Int,
    val locationType: String,      // "urban", "rural", "semi-urban"
    val language: String,           // "en", "hi", etc.
    val digitalLiteracy: String     // "low", "medium", "high"
)

/**
 * Customer-facing explanation generated by LumeAI
 */
data class CustomerExplanation(
    val summaryEnglish: String,
    val summaryHindi: String,
    val factors: List<ExplainedFactor>,
    val biasWarning: BiasWarning?,
    val nextSteps: List<ActionableStep>,
    val appealInfo: AppealInfo
)

/**
 * Explained factor in simple language
 */
data class ExplainedFactor(
    val friendlyName: String,
    val impact: String,          // "HIGH", "MEDIUM", "LOW"
    val status: String,          // "✓ Met", "✗ Not Met"
    val yourValue: String,
    val required: String,
    val explanation: String,
    val actionableStep: String?
)

/**
 * Bias warning for customers
 */
data class BiasWarning(
    val severity: String,
    val message: String,
    val affectedGroups: List<String>,
    val mitigationSteps: List<String>
)

/**
 * Actionable step customer can take
 */
data class ActionableStep(
    val title: String,
    val description: String,
    val estimatedImpact: String,
    val timeframe: String
)

/**
 * Information about appeal process
 */
data class AppealInfo(
    val canAppeal: Boolean,
    val process: String,
    val timeframe: String,
    val requiredDocuments: List<String>
)

