package com.lumeai.banking.models

import com.google.firebase.database.IgnoreExtraProperties

/**
 * Firebase-compatible decision model for real-time sync between bank and customer
 */
@IgnoreExtraProperties
data class FirebaseDecision(
    val id: String = "",
    val customerId: String = "",
    val customerName: String = "",
    val bankName: String = "",
    val decisionType: String = "", // "LOAN", "CREDIT_CARD", "ACCOUNT"
    val outcome: String = "", // "APPROVED", "DENIED", "PENDING"
    val timestamp: Long = 0L,
    val status: String = "pending", // "pending", "processing", "completed"
    
    // Loan details (NEW - for multi-loan support)
    val loanType: String = "", // "PERSONAL_LOAN", "HOME_LOAN", "CAR_LOAN", "CREDIT_CARD"
    val loanAmount: Double = 0.0, // Requested amount
    val applicationId: String = "", // User-friendly reference number
    
    // Customer profile
    val age: Int = 0,
    val locationType: String = "", // "urban", "rural", "semi-urban"
    val digitalLiteracy: String = "", // "low", "medium", "high"
    
    // Decision factors (raw)
    val creditScore: Int = 0,
    val creditScoreRequired: Int = 0,
    val creditScorePassed: Boolean = false,
    
    val income: Double = 0.0,
    val incomeRequired: Double = 0.0,
    val incomePassed: Boolean = false,
    
    val debtRatio: Double = 0.0,
    val debtRatioRequired: Double = 0.0,
    val debtRatioPassed: Boolean = false,
    
    val employmentMonths: Int = 0,
    val employmentMonthsRequired: Int = 0,
    val employmentPassed: Boolean = false,
    
    val digitalFootprint: String = "", // "low", "medium", "high"
    val digitalFootprintRequired: String = "",
    val digitalFootprintPassed: Boolean = false,
    
    // Bias analysis
    val biasDetected: Boolean = false,
    val biasSeverity: String = "", // "LOW", "MEDIUM", "HIGH"
    val biasMessage: String = "",
    val biasAffectedGroups: String = "", // comma-separated
    
    // Explanation (generated by LumeAI)
    val summaryEnglish: String = "",
    val summaryHindi: String = "",
    val summaryTelugu: String = "",
    
    // Improvement Paths (for denied applications)
    val improvementPathsEnglish: String = "", // JSON string
    val improvementPathsHindi: String = "", // JSON string
    
    // Appeal
    val appealRequested: Boolean = false,
    val appealTimestamp: Long = 0L,
    
    // Notification
    val notificationSent: Boolean = false
) {
    // No-argument constructor for Firebase
    constructor() : this("")
    
    /**
     * Convert to BankDecision for processing
     */
    fun toBankDecision(): BankDecision {
        val factors = mutableListOf<RawDecisionFactor>()
        
        if (creditScore > 0) {
            factors.add(RawDecisionFactor(
                technicalName = "credit_score",
                value = creditScore.toString(),
                weight = 0.35,
                threshold = creditScoreRequired.toString(),
                passed = creditScorePassed
            ))
        }
        
        if (income > 0) {
            factors.add(RawDecisionFactor(
                technicalName = "monthly_income",
                value = income.toString(),
                weight = 0.25,
                threshold = incomeRequired.toString(),
                passed = incomePassed
            ))
        }
        
        if (debtRatio > 0) {
            factors.add(RawDecisionFactor(
                technicalName = "debt_to_income_ratio",
                value = debtRatio.toString(),
                weight = 0.20,
                threshold = debtRatioRequired.toString(),
                passed = debtRatioPassed
            ))
        }
        
        if (employmentMonths > 0) {
            factors.add(RawDecisionFactor(
                technicalName = "employment_tenure",
                value = "$employmentMonths months",
                weight = 0.10,
                threshold = "$employmentMonthsRequired months",
                passed = employmentPassed
            ))
        }
        
        if (digitalFootprint.isNotEmpty()) {
            factors.add(RawDecisionFactor(
                technicalName = "digital_footprint",
                value = digitalFootprint,
                weight = 0.10,
                threshold = digitalFootprintRequired,
                passed = digitalFootprintPassed
            ))
        }
        
        // Create proper decision type based on outcome
        val properDecisionType = when (outcome.uppercase()) {
            "DENIED" -> "LOAN_DENIED"
            "APPROVED" -> "LOAN_APPROVED"
            "BLOCKED" -> "TRANSACTION_BLOCKED"
            "REDUCED" -> "CREDIT_LIMIT_REDUCED"
            else -> "LOAN_${outcome.uppercase()}"
        }
        
        return BankDecision(
            customerId = customerId,
            decisionType = properDecisionType,
            timestamp = timestamp,
            factors = factors,
            customerProfile = CustomerProfile(
                age = age,
                locationType = locationType,
                language = "en", // Can be made dynamic
                digitalLiteracy = digitalLiteracy
            )
        )
    }
}

/**
 * Simplified application model for bank portal
 */
data class LoanApplication(
    val id: String = "",
    val customerName: String,
    val customerId: String,
    val age: Int,
    val locationType: String,
    val digitalLiteracy: String,
    val creditScore: Int,
    val monthlyIncome: Double,
    val monthlyDebt: Double,
    val employmentMonths: Int,
    val digitalFootprint: String,
    val bankName: String = "HDFC Bank",
    val loanType: String = "PERSONAL_LOAN", // NEW
    val loanAmount: Double = 0.0 // NEW
) {
    /**
     * Calculate debt-to-income ratio
     */
    fun calculateDebtRatio(): Double = if (monthlyIncome > 0) monthlyDebt / monthlyIncome else 0.0
    
    /**
     * Convert to Firebase decision with requirements
     */
    fun toFirebaseDecision(decisionId: String): FirebaseDecision {
        val debtRatio = calculateDebtRatio()
        
        return FirebaseDecision(
            id = decisionId,
            customerId = customerId,
            customerName = customerName,
            bankName = bankName,
            decisionType = "LOAN",
            outcome = "PENDING",
            timestamp = System.currentTimeMillis(),
            status = "pending",
            
            loanType = loanType,
            loanAmount = loanAmount,
            applicationId = decisionId.take(12), // Short reference
            
            age = age,
            locationType = locationType,
            digitalLiteracy = digitalLiteracy,
            
            creditScore = creditScore,
            creditScoreRequired = 650,
            creditScorePassed = creditScore >= 650,
            
            income = monthlyIncome,
            incomeRequired = 30000.0,
            incomePassed = monthlyIncome >= 30000,
            
            debtRatio = debtRatio,
            debtRatioRequired = 0.40,
            debtRatioPassed = debtRatio <= 0.40,
            
            employmentMonths = employmentMonths,
            employmentMonthsRequired = 12,
            employmentPassed = employmentMonths >= 12,
            
            digitalFootprint = digitalFootprint,
            digitalFootprintRequired = "medium",
            digitalFootprintPassed = digitalFootprint != "low"
        )
    }
}

/**
 * Fraud Alert model for real-time fraud detection monitoring
 */
@IgnoreExtraProperties
data class FraudAlert(
    val id: String = "",
    val customerId: String = "",
    val customerName: String = "",
    val bankName: String = "",
    val timestamp: Long = 0L,
    
    // Transaction details
    val transactionId: String = "",
    val transactionType: String = "", // "TRANSFER", "PAYMENT", "WITHDRAWAL", "PURCHASE"
    val amount: Double = 0.0,
    val currency: String = "INR",
    val merchantName: String = "",
    val merchantCategory: String = "", // "retail", "online", "international", "atm"
    val location: String = "",
    val deviceId: String = "",
    
    // Fraud detection
    val riskLevel: String = "", // "LOW", "MEDIUM", "HIGH", "CRITICAL"
    val riskScore: Double = 0.0, // 0-100
    val fraudDetected: Boolean = false,
    val status: String = "", // "FLAGGED", "BLOCKED", "APPROVED", "UNDER_REVIEW"
    
    // AI Decision factors
    val unusualAmount: Boolean = false,
    val unusualLocation: Boolean = false,
    val unusualTime: Boolean = false,
    val newMerchant: Boolean = false,
    val multipleAttempts: Boolean = false,
    val deviceMismatch: Boolean = false,
    
    // Explanations
    val reasonEnglish: String = "",
    val reasonHindi: String = "",
    val reasonTelugu: String = "",
    val recommendationEnglish: String = "",
    val recommendationHindi: String = "",
    val recommendationTelugu: String = "",
    
    // User actions
    val userNotified: Boolean = false,
    val userConfirmed: Boolean = false,
    val userReportedFraud: Boolean = false
) {
    constructor() : this("")
}

/**
 * Personalized Offer model for AI-driven product recommendations
 */
@IgnoreExtraProperties
data class PersonalizedOffer(
    val id: String = "",
    val customerId: String = "",
    val customerName: String = "",
    val bankName: String = "",
    val timestamp: Long = 0L,
    val expiryTimestamp: Long = 0L,
    
    // Offer details
    val offerType: String = "", // "CREDIT_CARD", "PERSONAL_LOAN", "HOME_LOAN", "INVESTMENT", "INSURANCE", "SAVINGS_ACCOUNT"
    
    // Multilingual titles
    val offerTitle: String = "",  // English (default)
    val offerTitleHindi: String = "",
    val offerTitleTelugu: String = "",
    
    // Multilingual product names
    val productName: String = "",  // English (default)
    val productNameHindi: String = "",
    val productNameTelugu: String = "",
    
    val productDescription: String = "",
    val offerSubtitle: String = "",
    val offerImageUrl: String = "",
    
    // Benefits
    val interestRate: Double = 0.0,
    val processingFee: Double = 0.0,
    val cashback: Double = 0.0,
    val rewardPoints: Int = 0,
    val preApproved: Boolean = false,
    val instantApproval: Boolean = false,
    val eligibleAmount: Double = 0.0,
    
    // AI Transparency - Why this offer?
    val aiReasonEnglish: String = "",
    val aiReasonHindi: String = "",
    val aiReasonTelugu: String = "",
    val personalizationFactors: List<String> = emptyList(), // e.g., ["credit_score", "spending_pattern", "income"]
    
    // Consent & Control
    val consentRequired: Boolean = true,
    val dataUsed: List<String> = emptyList(), // e.g., ["transaction_history", "credit_score", "income"]
    
    // Status
    val status: String = "", // "ACTIVE", "EXPIRED", "ACCEPTED", "REJECTED", "HIDDEN"
    val userViewed: Boolean = false,
    val userAccepted: Boolean = false,
    val userRejected: Boolean = false,
    val userHidden: Boolean = false,
    
    // Fairness
    val fairnessScore: Double = 100.0, // 0-100, 100 = completely fair
    val biasChecked: Boolean = false
) {
    constructor() : this("")
}

